package beacon

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"math/big"
	"slices"

	bn256 "github.com/ethereum/go-ethereum/crypto/bn256/cloudflare"
	"github.com/ipfs/go-log/v2"
	"go.uber.org/zap"

	"github.com/keep-network/keep-core/pkg/altbn128"
	beaconchain "github.com/keep-network/keep-core/pkg/beacon/chain"
	"github.com/keep-network/keep-core/pkg/beacon/dkg"
	"github.com/keep-network/keep-core/pkg/beacon/entry"
	"github.com/keep-network/keep-core/pkg/beacon/event"
	"github.com/keep-network/keep-core/pkg/beacon/registry"
	"github.com/keep-network/keep-core/pkg/chain"
	"github.com/keep-network/keep-core/pkg/generator"
	"github.com/keep-network/keep-core/pkg/net"
	"github.com/keep-network/keep-core/pkg/protocol/compatibility"
	"github.com/keep-network/keep-core/pkg/protocol/group"
	"github.com/keep-network/keep-core/pkg/protocol/participation"
)

// node represents the current state of a beacon node.
type node struct {
	beaconChain   beaconchain.Interface
	netProvider   net.Provider
	groupRegistry *registry.Groups
	protocolLatch *generator.ProtocolLatch

	// participationGate issues the per-ceremony participation permits that pin
	// each ceremony's protocol mode from its canonical chain anchor. It is
	// constructed once at process startup and shared with the tBTC
	// application.
	participationGate participation.Gate

	// signerQuarantine preserves signer outputs whose completion the gate
	// interrupted before an accepted on-chain publication was observed. It
	// writes to a dedicated protected namespace outside the active-group scan.
	signerQuarantine *registry.Quarantine
}

func beaconDKGPermitIdentity(
	seed *big.Int,
	memberIndex group.MemberIndex,
) participation.PermitIdentity {
	seedHash := sha256.Sum256(seed.Bytes())
	return participation.PermitIdentity{
		WorkID:   hex.EncodeToString(seedHash[:]),
		PermitID: fmt.Sprint(memberIndex),
		// The one seat this permit runs. The beacon group index is the DKG
		// index, so this is also the seat the persisted signer will carry.
		OperatedMembers: participation.MemberIndexes{memberIndex},
	}
}

// beaconRelayPermitIdentity binds a relay permit to the request it answers.
// operatedMembers is the seat the permit runs for a signing membership, and
// empty for the relay permits that operate no seat — a forwarder relays other
// members' shares and computes nothing, and a timeout monitor files a penalty
// rather than a contribution.
func beaconRelayPermitIdentity(
	requestStartBlock uint64,
	localPermitID string,
	operatedMembers ...group.MemberIndex,
) participation.PermitIdentity {
	return participation.PermitIdentity{
		WorkID:          participation.BeaconRelayWorkID(requestStartBlock),
		PermitID:        localPermitID,
		OperatedMembers: participation.MemberIndexes(operatedMembers),
	}
}

// newNode returns an empty node with no group, zero group count, and a nil last
// seen entry, tied to the given net.Provider.
func newNode(
	beaconChain beaconchain.Interface,
	netProvider net.Provider,
	groupRegistry *registry.Groups,
	scheduler *generator.Scheduler,
	participationGate participation.Gate,
	signerQuarantine *registry.Quarantine,
) *node {
	latch := generator.NewProtocolLatch()
	scheduler.RegisterProtocol(latch)

	return &node{
		beaconChain:       beaconChain,
		netProvider:       netProvider,
		groupRegistry:     groupRegistry,
		protocolLatch:     latch,
		participationGate: participationGate,
		signerQuarantine:  signerQuarantine,
	}
}

// IsInGroup checks if this node is a member of the group which was selected to
// join a group which undergoes the process of generating a threshold relay entry.
func (n *node) IsInGroup(groupPublicKey []byte) bool {
	return len(n.groupRegistry.GetGroup(groupPublicKey)) > 0
}

// JoinDKGIfEligible takes a seed value and undergoes the process of the
// distributed key generation if this node's operator proves to be eligible for
// the group generated by that seed. This is an interactive on-chain process,
// and JoinDKGIfEligible can block for an extended period of time while it
// completes the on-chain operation.
func (n *node) JoinDKGIfEligible(
	dkgSeed *big.Int,
	dkgStartBlockNumber uint64,
) {
	dkgLogger := logger.With(
		zap.String("seed", fmt.Sprintf("0x%x", dkgSeed)),
	)

	dkgLogger.Info("checking eligibility for DKG")

	selectedOperators, err := n.beaconChain.SelectGroup(dkgSeed)
	if err != nil {
		// TODO: We should consider switching this log to Errorf when the
		// Chaosnet 0 phase is completed and results are submitted to the chain.
		// To let the operators join the pool, the dev team will keep unlocking
		// it via DKG timeout from time to time. During the period pool is
		// unlocked, selecting the group will not work.
		//dkgLogger.Errorf("failed to select group: [%v]", err)
		dkgLogger.Warnf("selecting group not possible: [%v]", err)
		return
	}

	dkgLogger.Infof("selected group members for DKG = %s", selectedOperators)

	if len(selectedOperators) > n.beaconChain.GetConfig().GroupSize {
		dkgLogger.Errorf(
			"group size larger than supported: [%v]",
			len(selectedOperators),
		)
		return
	}

	signing := n.beaconChain.Signing()

	_, operatorPublicKey, err := n.beaconChain.OperatorKeyPair()
	if err != nil {
		dkgLogger.Errorf("failed to get operator public key: [%v]", err)
		return
	}

	operatorAddress, err := signing.PublicKeyToAddress(operatorPublicKey)
	if err != nil {
		dkgLogger.Errorf("failed to get operator address: [%v]", err)
		return
	}

	indexes := make([]uint8, 0)
	for index, selectedOperator := range selectedOperators {
		// See if we are amongst those chosen
		if selectedOperator == operatorAddress {
			indexes = append(indexes, uint8(index))
		}
	}

	// Create temporary broadcast channel name for DKG using the
	// group selection seed with the protocol name as prefix.
	channelName := fmt.Sprintf("%s-%s", ProtocolName, dkgSeed.Text(16))

	if len(indexes) > 0 {
		dkgLogger.Infof(
			"joining DKG and controlling [%v] group members",
			len(indexes),
		)

		if n.participationGate == nil {
			// The gate is mandatory in production; participating without it
			// would select a protocol mode implicitly. Fail closed.
			dkgLogger.Errorf(
				"no participation gate; refusing to join DKG",
			)
			return
		}

		if n.signerQuarantine == nil {
			// Without a quarantine store a gate interruption after key
			// generation would have to drop the generated share. Fail closed.
			dkgLogger.Errorf(
				"no signer quarantine store; refusing to join DKG",
			)
			return
		}

		broadcastChannel, err := n.netProvider.BroadcastChannelFor(channelName)
		if err != nil {
			dkgLogger.Errorf("failed to get broadcast channel: [%v]", err)
			return
		}

		membershipValidator := group.NewMembershipValidator(
			dkgLogger,
			selectedOperators,
			signing,
		)

		err = broadcastChannel.SetFilter(membershipValidator.IsInGroup)
		if err != nil {
			dkgLogger.Errorf(
				"could not set filter for channel [%v]: [%v]",
				broadcastChannel.Name(),
				err,
			)
		}

		for _, index := range indexes {
			// Capture the member index for the goroutine. The group member
			// index should be in range [1, groupSize] so we need to add 1.
			memberIndex := index + 1

			// One participation permit per locally controlled member, issued
			// immediately before the member goroutine. The permit pins the
			// protocol mode from the ceremony's canonical chain anchor — the
			// DKG started event block — for the ceremony's entire lifetime,
			// and every wire-sensitive choice derives from the bundle it
			// selects. A refusal is a gate decision, not an ordinary DKG
			// failure.
			permit, err := n.participationGate.Begin(
				participation.BeaconDKG,
				dkgStartBlockNumber,
				beaconDKGPermitIdentity(dkgSeed, memberIndex),
			)
			if err != nil {
				dkgLogger.Warnf(
					"[member:%v] refused by the participation gate: [%v]",
					memberIndex,
					err,
				)
				continue
			}

			strategies, err := compatibility.StrategiesFor(permit.Mode())
			if err != nil {
				// Unreachable with a well-formed permit; refusing to
				// participate is the only safe response to a mode without an
				// explicit bundle.
				permit.Close()
				dkgLogger.Errorf(
					"[member:%v] no compatibility strategies for the "+
						"permitted mode: [%v]",
					memberIndex,
					err,
				)
				continue
			}

			go func() {
				defer permit.Close()

				n.protocolLatch.Lock()
				defer n.protocolLatch.Unlock()

				dkgLogger.Infof(
					"[member:%v] joining DKG with protocol mode [%s] "+
						"[canonicalStartBlock=%v]",
					memberIndex,
					permit.Mode(),
					permit.CanonicalStartBlock(),
				)

				signer, operatingMembers, err := dkg.ExecuteDKG(
					permit.Context(),
					dkgLogger,
					dkgSeed,
					memberIndex,
					dkgStartBlockNumber,
					n.beaconChain,
					broadcastChannel,
					membershipValidator,
					selectedOperators,
					strategies,
					permit,
				)
				if err != nil {
					var interrupted *dkg.PublicationInterruptedError
					switch {
					case errors.As(err, &interrupted):
						// The gate stopped the ceremony after key generation
						// but before an accepted publication was observed:
						// preserve the orphaned share for the offline audit.
						n.quarantineSigner(
							dkgLogger,
							dkgSeed,
							memberIndex,
							interrupted,
							permit,
						)
					case participation.IsGateRefusal(err):
						// A gate decision before key generation is not an
						// ordinary DKG failure.
						dkgLogger.Warnf(
							"[member:%v] DKG canceled by the participation "+
								"gate: [%v]",
							memberIndex,
							err,
						)
					default:
						dkgLogger.Errorf("failed to execute dkg: [%v]", err)
					}
					return
				}

				groupPublicKey := hex.EncodeToString(
					signer.GroupPublicKeyBytesCompressed(),
				)

				// The result reached the chain, so the share must be preserved
				// durably in every outcome. The fence decides only whether this
				// process may also activate it now: during quiescence or after
				// a clock failure the accepted share is saved without
				// activation and loads as active on the next start.
				err = permit.CheckCommit(
					"beacon_dkg_signer_activation",
					participation.CompletionCommit,
				)
				if err != nil {
					dkgLogger.Warnf(
						"[member:%v] activation of group [0x%v] refused by "+
							"the release gate; preserving the accepted signer "+
							"without activation: [%v]",
						signer.MemberID(),
						groupPublicKey,
						err,
					)
					if saveErr := n.groupRegistry.SaveAcceptedGroup(
						signer,
						groupPublicKey,
					); saveErr != nil {
						dkgLogger.Errorf(
							"[member:%v] failed to preserve the accepted "+
								"signer of group [0x%v]; the share is only "+
								"in memory: [%v]",
							signer.MemberID(),
							groupPublicKey,
							saveErr,
						)
					} else {
						recordBeaconPermitTerminalOutcome(
							dkgLogger,
							permit,
							participation.TerminalOutcomeCompleted,
							participation.TerminalEvidence{
								Kind:            participation.TerminalEvidencePersistedBeaconSigner,
								Reference:       groupPublicKey,
								MembershipIndex: signer.MemberID(),
								Contribution: beaconDKGTranscriptContribution(
									signer,
									operatingMembers,
								),
							},
						)
					}
					return
				}

				err = n.groupRegistry.RegisterGroup(signer, groupPublicKey)
				if err != nil {
					dkgLogger.Errorf(
						"[member:%v] failed to register a group [0x%v]: [%v]",
						signer.MemberID(),
						groupPublicKey,
						err,
					)
					return
				}

				dkgLogger.Infof(
					"[member:%v] group [0x%v] registered successfully",
					signer.MemberID(),
					groupPublicKey,
				)
				recordBeaconPermitTerminalOutcome(
					dkgLogger,
					permit,
					participation.TerminalOutcomeCompleted,
					participation.TerminalEvidence{
						Kind:            participation.TerminalEvidencePersistedBeaconSigner,
						Reference:       groupPublicKey,
						MembershipIndex: signer.MemberID(),
						Contribution: beaconDKGTranscriptContribution(
							signer,
							operatingMembers,
						),
					},
				)
			}()
		}
	} else {
		dkgLogger.Infof("not eligible for DKG")
	}
}

// quarantineSigner preserves a signer output whose publication the release
// gate interrupted. The share may still be part of a result other members
// published, so it cannot be dropped, and no acceptance was observed locally,
// so it must not be activated; the offline state audit reconciles it against
// the chain. A preservation failure is a WARN-level protocol violation and is
// never suppressed.
func (n *node) quarantineSigner(
	dkgLogger log.StandardLogger,
	dkgSeed *big.Int,
	memberIndex group.MemberIndex,
	interrupted *dkg.PublicationInterruptedError,
	permit participation.Permit,
) {
	dkgLogger.Warnf(
		"[member:%v] DKG interrupted by the participation gate after key "+
			"generation; quarantining the signer output: [%v]",
		memberIndex,
		interrupted.Cause,
	)

	gateSnapshot := n.participationGate.State()

	channelName := hex.EncodeToString(
		interrupted.Signer.GroupPublicKeyBytesCompressed(),
	)
	seedHash := sha256.Sum256(dkgSeed.Bytes())

	state, err := n.signerQuarantine.Preserve(
		&registry.Membership{
			Signer:      interrupted.Signer,
			ChannelName: channelName,
		},
		registry.QuarantinedSignerMetadata{
			ReleaseEpoch:        participation.CompiledEpoch.String(),
			ProtocolMode:        permit.Mode().String(),
			CutoverBlock:        gateSnapshot.CutoverBlock,
			CanonicalStartBlock: permit.CanonicalStartBlock(),
			Ceremony:            string(permit.Ceremony()),
			SeedHash:            hex.EncodeToString(seedHash[:]),
			FailedOperation:     "beacon_dkg_result_publication",
			LastObservedBlock:   gateSnapshot.CurrentBlock,
		},
		// Preservation keeps running behind this. It fires once the namespace
		// has refused a half for longer than a passing fault would last, so the
		// node stops taking new work while it is still holding an output the
		// namespace does not fully have.
		func(state registry.QuarantineState, cause error) {
			n.blockOnIncompleteQuarantine(
				dkgLogger,
				memberIndex,
				state,
				cause,
			)
		},
	)

	// The terminal outcome needs the whole output. The audit record is what
	// names the mode, canonical anchor, ceremony, seat, and refused operation of
	// the preserved share; without it the offline audit cannot reconcile the
	// material against the chain, so calling the permit resolved would hand the
	// rollback decision a quarantine nothing explains. Either form the namespace
	// took it whole in settles this — the record pair or the single handoff
	// carrying both. Anything less leaves the permit unresolved, and the offline
	// barrier keeps blocking on it until an operator repairs the namespace.
	if !state.Complete() {
		n.blockOnIncompleteQuarantine(dkgLogger, memberIndex, state, err)
		return
	}

	recordBeaconPermitTerminalOutcome(
		dkgLogger,
		permit,
		participation.TerminalOutcomeQuarantined,
		participation.TerminalEvidence{
			Kind: participation.TerminalEvidenceQuarantinedBeaconSigner,
		},
	)
}

// blockOnIncompleteQuarantine stops this node from beginning new ceremonies
// while a preserved output is missing a half the namespace was supposed to hold.
//
// Either half missing leaves an inventory a rollback cannot reconcile, and a
// beacon share is worse to be unsure about than a tBTC one: the group it belongs
// to may already have an accepted result, and a member that cannot produce its
// share permanently reduces that group's usable threshold. A share that reached
// no namespace exists only in the goroutine that generated it. A share preserved
// without its audit metadata is on disk but unexplained: the mode, canonical
// anchor, ceremony, seat, and refused operation that would let the audit match
// it against the chain are exactly what did not land.
//
// Quiescence is the blocking state rather than a new one of its own: it refuses
// every new permit, it is already what the gate-state gauge and the quiesce
// counter report, and it lets the permits still running finish normally. It is
// one-way by design — an operator restarts the node once the namespace is
// repaired — which is also why the preservation behind it is given a grace
// budget first, so a namespace that clears on its own does not cost the fleet a
// node. No terminal outcome is recorded, so this permit closes unresolved and
// blocks the offline barrier on its own.
//
// The returned channel is deliberately ignored. This caller holds a permit of
// its own, so waiting for the active permit count to reach zero here would be
// waiting for itself.
func (n *node) blockOnIncompleteQuarantine(
	dkgLogger log.StandardLogger,
	memberIndex group.MemberIndex,
	state registry.QuarantineState,
	cause error,
) {
	if state.KeyMaterialPersisted() {
		dkgLogger.Errorf(
			"[member:%v] the quarantined signer output has no audit record "+
				"explaining it; the share is preserved but a rollback cannot "+
				"reconcile it without the record; refusing new ceremonies on "+
				"this node until an operator repairs the quarantine "+
				"namespace: [%v]",
			memberIndex,
			cause,
		)
	} else {
		dkgLogger.Errorf(
			"[member:%v] generated key material reached no namespace; the "+
				"share is only in memory [auditMetadataPreserved=%v]; "+
				"refusing new ceremonies on this node until an operator "+
				"resolves the quarantine namespace: [%v]",
			memberIndex,
			state.MetadataPersisted,
			cause,
		)
	}

	if n.participationGate == nil {
		return
	}

	n.participationGate.Quiesce(fmt.Errorf(
		"beacon key material could not be preserved with its audit record: [%w]",
		cause,
	))
}

// beaconDKGTranscriptContribution renders the memberships that produced a DKG
// result: the members the key material was generated with, and this node's own
// seat among them.
//
// The local half is the seat this permit was issued for rather than every seat
// this node holds in the group. Each locally controlled member runs its own DKG
// under its own permit and publishes its own record, so the fleet's own
// memberships are covered by the union of those records; a permit may only
// speak for the ceremony it ran.
//
// A seat missing from the operating members is not written down as local. The
// gate refuses a transcript whose local memberships are not among the ones that
// produced the result, and a signer persisted from a ceremony that did not
// include it is incoherent rather than something to record — so the record fails
// closed and the offline barrier blocks on the permit instead.
func beaconDKGTranscriptContribution(
	signer *dkg.ThresholdSigner,
	operatingMembers participation.MemberIndexes,
) *participation.TranscriptContribution {
	local := make(participation.MemberIndexes, 0, 1)
	if slices.Contains(operatingMembers, signer.MemberID()) {
		local = append(local, signer.MemberID())
	}

	return &participation.TranscriptContribution{
		IncorporatedMembers: operatingMembers,
		LocalMembers:        local,
	}
}

func recordBeaconPermitTerminalOutcome(
	dkgLogger log.StandardLogger,
	permit participation.Permit,
	outcome participation.TerminalOutcome,
	evidence participation.TerminalEvidence,
) {
	if err := permit.RecordTerminalOutcome(outcome, evidence); err != nil {
		dkgLogger.Warnf(
			"could not persist the node-authored beacon terminal outcome "+
				"[member=%s] [outcome=%s]: [%v]",
			permit.PermitID(),
			outcome,
			err,
		)
	}
}

// recordBeaconPermitNoThreshold records that a beacon ceremony ended without
// producing a threshold result or any durable state transition this node owns.
// It is the honest disposition for a ceremony another member finished first,
// one that timed out, and one the release gate canceled.
func recordBeaconPermitNoThreshold(
	beaconLogger log.StandardLogger,
	permit participation.Permit,
) {
	recordBeaconPermitTerminalOutcome(
		beaconLogger,
		permit,
		participation.TerminalOutcomeExhausted,
		participation.TerminalEvidence{
			Kind: participation.TerminalEvidenceNoThreshold,
		},
	)
}

// recordRelayTimeoutTerminalOutcome reports the relay entry monitor's
// node-owned final disposition. The monitor exists only to file the penalty
// report, so the beacon's own record of the terminated request is its durable
// result; a monitor that ended because the group delivered on time, because the
// report failed, or because the release gate canceled it created no penalty
// state and is recorded as exhausted.
//
// A report the node merely handed to a provider is not a result. The submitting
// call returns before the transaction is mined and a transaction that reverts,
// is dropped, or never lands leaves the beacon exactly as it was, so only the
// settlement the beacon itself recorded settles the permit as completed.
// Reading the node's own submission as the penalty would let a failed report
// clear the rollback barrier that exists to hold it.
//
// The evidence carries the beacon's request identifier and terminated group
// rather than a digest of the request this node was watching. Those two fields
// are what a RelayEntryTimedOut log is made of, so the offline audit joins the
// record to an authenticated log instead of checking that a node stayed
// consistent with itself. A settlement whose reference cannot be rendered is
// recorded as exhausted: an unrenderable identity is one the audit could not
// reconcile, and a penalty the audit cannot reconcile has to keep holding the
// barrier.
func recordRelayTimeoutTerminalOutcome(
	monitorLogger log.StandardLogger,
	permit participation.Permit,
	relayRequestBlockNumber uint64,
	settlement *event.RelayEntryTimeoutSettlement,
) {
	if settlement == nil {
		recordBeaconPermitNoThreshold(monitorLogger, permit)
		return
	}

	reference, err := participation.BeaconRelayTimeoutSettlementReference(
		relayRequestBlockNumber,
		settlement.RequestID,
		settlement.TerminatedGroupID,
	)
	if err != nil {
		monitorLogger.Errorf(
			"the beacon's timeout settlement for the relay request of block "+
				"[%v] has no canonical identity; the report is recorded as "+
				"unsettled: [%v]",
			relayRequestBlockNumber,
			err,
		)
		recordBeaconPermitNoThreshold(monitorLogger, permit)
		return
	}

	recordBeaconPermitTerminalOutcome(
		monitorLogger,
		permit,
		participation.TerminalOutcomeCompleted,
		participation.TerminalEvidence{
			Kind:      participation.TerminalEvidenceEthereumTransaction,
			Reference: reference,
		},
	)
}

// relayEntryTimeoutReportResolutionBlocks bounds how long the monitor asks the
// beacon whether the timeout report it filed was accepted. The submitting call
// returns once the transaction reaches the provider and the transaction mines
// afterwards, so the report's effect is not visible on the first read. The
// bound is generous enough for an ordinary inclusion; the permit's context cuts
// the wait short in any case.
const relayEntryTimeoutReportResolutionBlocks = 12

// errRelayEntryDeadlineOverflow reports a block deadline the block range cannot
// represent. Both deadlines the relay entry monitor derives are rejected on
// overflow rather than clamped: a wrapped deadline names a block already in the
// past, and every use of one here is a fence that would silently open.
var errRelayEntryDeadlineOverflow = errors.New(
	"the block deadline is not representable",
)

// relayEntryTimeoutBlock returns the block at which the selected group has run
// out of time to deliver, or rejects a sum the block range cannot represent.
//
// The rejection is what keeps the monitor from filing a penalty nobody earned.
// A wrapped timeout block names a block the chain already passed, so the waiter
// on it fires at once and the monitor reports a request that has had no chance
// to be answered. The report is the irreversible step, so the arithmetic that
// authorizes it is checked before the monitor commits to running at all.
func relayEntryTimeoutBlock(
	relayRequestBlockNumber uint64,
	relayEntryTimeout uint64,
) (uint64, error) {
	if relayRequestBlockNumber > math.MaxUint64-relayEntryTimeout {
		return 0, fmt.Errorf(
			"%w: relay request block [%v] plus the relay entry timeout of "+
				"[%v] blocks",
			errRelayEntryDeadlineOverflow,
			relayRequestBlockNumber,
			relayEntryTimeout,
		)
	}
	return relayRequestBlockNumber + relayEntryTimeout, nil
}

// relayEntryTimeoutReportResolutionDeadline returns the block the monitor stops
// asking the beacon about a filed report at, or rejects a sum the block range
// cannot represent.
//
// A wrapped bound reads as already reached, which would end the reconciliation
// before the beacon could answer and leave the permit exhausted. Rejecting it
// reaches the same disposition without pretending a bounded observation
// happened, and clamping it to the top of the range instead would widen the
// window silently.
func relayEntryTimeoutReportResolutionDeadline(
	currentBlock uint64,
) (uint64, error) {
	if currentBlock > math.MaxUint64-relayEntryTimeoutReportResolutionBlocks {
		return 0, fmt.Errorf(
			"%w: current block [%v] plus the [%v] block report resolution "+
				"bound",
			errRelayEntryDeadlineOverflow,
			currentBlock,
			relayEntryTimeoutReportResolutionBlocks,
		)
	}
	return currentBlock + relayEntryTimeoutReportResolutionBlocks, nil
}

// relayTimeoutReportSettled asks the beacon whether the relay request this
// monitor reported a timeout for was terminated because of the report, and
// returns the beacon's own record of that termination.
//
// A filed report is not a penalty. The submitting call returns once the
// transaction reaches a provider; a transaction that reverts, is dropped, or
// loses the race to another reporter leaves the beacon exactly as it was. Only
// the beacon says whether a penalty exists, so the monitor asks it and claims
// nothing it cannot read back.
//
// What it asks for is the beacon's own settlement record, not an inference from
// the in-flight request slot. The slot cannot carry the answer: a relay entry
// delivered late empties the very same slot an accepted report empties, and a
// chain view taken before the request was made is an empty slot naming the very
// previous entry the request went on to sign over. Telling those apart needs
// history the node accumulated across reads, and process-local history is not a
// canonical binding — a reorg that removes the request leaves the node's memory
// of having seen it intact, and the reading it authorizes then manufactures a
// penalty out of a chain state that no longer exists.
//
// A settlement record has no such gap. It is resolved from canonical logs on
// every call, and every component — the terminated request, the terminating
// log — has to be present in the same view for the record to exist at all. A
// reorg that removes either takes the record with it, so a claim can never
// outlive the chain state it rests on. It is also what the offline audit needs:
// the record names an authenticated log the audit can join to, instead of a
// digest this node derived from its own request.
//
// The subscription is still read, but only to refuse faster: an entry seen at
// any point ends the reconciliation against the report. It can never be what
// establishes one.
//
// Every other reading is a refusal to claim the penalty: an unreadable beacon,
// a chain that exposes no settlement records at all, a record that does not
// answer the request the monitor asked about, a beacon that recorded nothing by
// the time the wait runs out, and a resolution bound that cannot be represented
// all leave the permit exhausted. That direction is the safe one — the rollback
// barrier exists to hold a penalty nobody can account for, so an unproven report
// has to keep holding it.
func (n *node) relayTimeoutReportSettled(
	ctx context.Context,
	monitorLogger log.StandardLogger,
	blockCounter chain.BlockCounter,
	relayRequestBlockNumber uint64,
	relayRequestPreviousEntry []byte,
	entries <-chan *event.RelayEntrySubmitted,
) *event.RelayEntryTimeoutSettlement {
	// The beacon identifies the terminated request by the previous entry it was
	// signing over, so without that entry there is no request to ask about.
	// Refusing here says so plainly instead of polling to a deadline.
	if len(relayRequestPreviousEntry) == 0 {
		monitorLogger.Warnf(
			"the relay request of block [%v] names no previous entry; the "+
				"filed timeout report cannot be reconciled against the beacon "+
				"and is not claimed as settled",
			relayRequestBlockNumber,
		)
		return nil
	}

	// entryDelivered reports whether the group submitted a relay entry. The
	// read is non-blocking: the subscription's buffered channel holds a
	// delivery that arrived while this loop was elsewhere, and an empty channel
	// means nothing has been delivered up to this point in the window.
	entryDelivered := func() bool {
		select {
		case entry := <-entries:
			monitorLogger.Warnf(
				"a relay entry was submitted at block [%v] while the filed "+
					"timeout report was being resolved; the group delivered, "+
					"so no timeout penalty is claimed",
				entry.BlockNumber,
			)
			return true
		default:
			return false
		}
	}

	// answersReportedRequest holds the beacon's record to the request this
	// monitor was issued for. The chain handle is asked about one request, but
	// a record that answers another one is a real penalty this permit did not
	// earn, so the binding is checked here rather than assumed.
	answersReportedRequest := func(
		settlement *event.RelayEntryTimeoutSettlement,
	) error {
		if settlement.RequestID == nil {
			return fmt.Errorf("the settlement names no request identifier")
		}
		if settlement.RequestBlockNumber != relayRequestBlockNumber {
			return fmt.Errorf(
				"the settlement terminates the request of block [%v]",
				settlement.RequestBlockNumber,
			)
		}
		if !bytes.Equal(
			settlement.RequestPreviousEntry,
			relayRequestPreviousEntry,
		) {
			return fmt.Errorf(
				"the settlement terminates a request signing over a different " +
					"previous entry",
			)
		}
		return nil
	}

	currentBlock, err := blockCounter.CurrentBlock()
	if err != nil {
		monitorLogger.Warnf(
			"cannot get the current block to resolve the relay entry "+
				"timeout report; the report is not claimed as settled: [%v]",
			err,
		)
		return nil
	}

	deadline, err := relayEntryTimeoutReportResolutionDeadline(currentBlock)
	if err != nil {
		monitorLogger.Warnf(
			"cannot bound the relay entry timeout report resolution; the "+
				"report is not claimed as settled: [%v]",
			err,
		)
		return nil
	}

	for {
		if entryDelivered() {
			return nil
		}

		settlement, err := n.beaconChain.RelayEntryTimeoutSettlement(
			relayRequestBlockNumber,
			relayRequestPreviousEntry,
		)
		if err != nil {
			monitorLogger.Warnf(
				"cannot read the beacon's record of the relay entry timeout "+
					"report; the report is not claimed as settled: [%v]",
				err,
			)
			return nil
		}
		if settlement != nil {
			if err := answersReportedRequest(settlement); err != nil {
				monitorLogger.Warnf(
					"the beacon returned a timeout settlement that does not "+
						"answer the relay request of block [%v]; the filed "+
						"report is not claimed as settled: [%v]",
					relayRequestBlockNumber,
					err,
				)
				return nil
			}

			monitorLogger.Infof(
				"the beacon terminated group [%v] for the relay request of "+
					"block [%v] at block [%v]; the filed timeout report was "+
					"accepted",
				settlement.TerminatedGroupID,
				relayRequestBlockNumber,
				settlement.BlockNumber,
			)
			return settlement
		}

		// The beacon holds no record of the request being terminated. That is
		// every view the report has not been mined into yet, so the monitor
		// keeps asking to the bound.

		height, err := blockCounter.CurrentBlock()
		if err != nil {
			monitorLogger.Warnf(
				"cannot follow the chain while resolving the relay entry "+
					"timeout report; the report is not claimed as "+
					"settled: [%v]",
				err,
			)
			return nil
		}
		if height >= deadline {
			monitorLogger.Warnf(
				"the beacon did not record a penalty for the relay request "+
					"of block [%v] by block [%v]; the filed timeout report is "+
					"not claimed as settled",
				relayRequestBlockNumber,
				height,
			)
			return nil
		}

		if err := blockCounter.WaitForBlockHeight(height + 1); err != nil {
			monitorLogger.Warnf(
				"cannot wait for the next block while resolving the relay "+
					"entry timeout report; the report is not claimed as "+
					"settled: [%v]",
				err,
			)
			return nil
		}
		if ctx.Err() != nil {
			monitorLogger.Warnf(
				"relay entry timeout report resolution ended before the "+
					"beacon confirmed it: [%v]",
				context.Cause(ctx),
			)
			return nil
		}
	}
}

// recordRelayEntryTerminalOutcome reports one relay signing membership's
// node-owned final disposition. A relay entry is deterministic for a given
// previous entry, so the recovered entry itself is the ceremony's durable
// result regardless of which member published it.
//
// The record names the group and the previous entry alongside it, because the
// entry alone is a bare byte string the node asserts. Named together they are a
// threshold BLS signature the offline audit can verify against a group public
// key it decoded from the snapshot's own key material, which no node can
// produce without that group's threshold key.
//
// It names the relay request start block too, because a valid signature says
// which group signed but not which request the result answers. The gate refuses
// a record whose request does not match the permit's own, so an entry recovered
// for one request cannot become another request's result.
func recordRelayEntryTerminalOutcome(
	relayLogger log.StandardLogger,
	permit participation.Permit,
	relayRequestStartBlock uint64,
	groupPublicKey []byte,
	previousEntry []byte,
	relayEntry []byte,
	incorporated participation.MemberIndexes,
	memberships []*registry.Membership,
) {
	if len(relayEntry) == 0 {
		recordBeaconPermitNoThreshold(relayLogger, permit)
		return
	}

	// The previous entry arrives from the chain, so it is normalized to the
	// canonical point encoding the audit compares against rather than trusted
	// to already be one. Signing has already parsed it as a point, so this
	// cannot fail for an entry that was actually signed.
	canonicalPreviousEntry := new(bn256.G1)
	if _, err := canonicalPreviousEntry.Unmarshal(previousEntry); err != nil {
		relayLogger.Errorf(
			"the previous entry this relay signed is not a curve point; the "+
				"membership's terminal outcome is left unresolved: [%v]",
			err,
		)
		return
	}

	reference, err := participation.BeaconRelayEntryReference(
		relayRequestStartBlock,
		groupPublicKey,
		canonicalPreviousEntry.Marshal(),
		relayEntry,
	)
	if err != nil {
		// An entry that cannot be named verifiably is worth less than no
		// claim of a result at all: recording it would put an unverifiable
		// digest where the audit expects a checkable one. The permit closes
		// unresolved and the offline barrier blocks on it.
		relayLogger.Errorf(
			"cannot name the recovered relay entry canonically; the "+
				"membership's terminal outcome is left unresolved: [%v]",
			err,
		)
		return
	}

	recordBeaconPermitTerminalOutcome(
		relayLogger,
		permit,
		participation.TerminalOutcomeCompleted,
		participation.TerminalEvidence{
			Kind:         participation.TerminalEvidenceProtocolResult,
			Reference:    reference,
			Contribution: relayTranscriptContribution(incorporated, memberships),
		},
	)
}

// relayTranscriptContribution renders the local view of who produced a relay
// entry: the memberships whose authenticated signature shares were combined
// into it, and the ones among them this node operates in that group.
//
// The local half is read from every membership this node holds in the group
// rather than from the one this permit was issued for. A node running several
// seats supplies several shares, and a record naming only its own seat would
// leave the rest looking like shares some other party had to supply — which is
// exactly the reading a fleet subtracting its own memberships from the
// incorporated population draws to find the parties outside it.
//
// What the incorporated half attests is bounded by the wire, and the bound is
// worth stating where the record is written. A share is authenticated against the
// group public key share published for the membership that sent it and against
// the previous entry being signed, and nothing in it names the request. A relay
// entry is deterministic in its previous entry, so a request that follows one
// which timed out without a submission signs the same previous entry, and a share
// belonging to either is valid for both. A seat named here therefore held the
// private share behind its membership and put it into this recovered entry; that
// it was live at this request's start block is more than the share can say.
// Binding the two would mean carrying the request anchor in the message, which is
// the wire change this release cannot make.
func relayTranscriptContribution(
	incorporated participation.MemberIndexes,
	memberships []*registry.Membership,
) *participation.TranscriptContribution {
	local := make(participation.MemberIndexes, 0, len(memberships))
	for _, membership := range memberships {
		memberID := membership.Signer.MemberID()
		if slices.Contains(incorporated, memberID) &&
			!slices.Contains(local, memberID) {
			local = append(local, memberID)
		}
	}
	slices.Sort(local)

	return &participation.TranscriptContribution{
		IncorporatedMembers: incorporated,
		LocalMembers:        local,
	}
}

// ForwardSignatureShares enables the ability to forward signature shares
// messages to other nodes even if this node is not a part of the group which
// signs the relay entry. The forwarding runs under a participation permit
// anchored at the relay request block, so quiescence and clock failure close
// the relay; the permit's mode is telemetry only because forwarding does not
// reinterpret payloads.
func (n *node) ForwardSignatureShares(
	groupPublicKeyBytes []byte,
	relayRequestBlockNumber uint64,
) {
	name, err := channelNameForPublicKeyBytes(groupPublicKeyBytes)
	if err != nil {
		logger.Warnf("could not forward signature shares: [%v]", err)
		return
	}

	if n.participationGate == nil {
		logger.Warnf(
			"no participation gate; not forwarding signature shares",
		)
		return
	}

	permit, err := n.participationGate.Begin(
		participation.BeaconRelayForwarding,
		relayRequestBlockNumber,
		beaconRelayPermitIdentity(relayRequestBlockNumber, "forwarder"),
	)
	if err != nil {
		logger.Warnf(
			"signature share forwarding refused by the participation "+
				"gate: [%v]",
			err,
		)
		return
	}

	forwarder, err := n.netProvider.BroadcastChannelForwarderFor(name)
	if err != nil {
		permit.Close()
		logger.Warnf(
			"could not start the message forwarder for channel [%v]: [%v]",
			name,
			err,
		)
		return
	}

	go func() {
		defer permit.Close()

		select {
		case <-forwarder.Done():
			// TTL expiry, provider shutdown, or an explicit close ended the
			// relay naturally.
		case <-permit.Context().Done():
			// Clock failure or forced quiescence closes the relay.
			forwarder.Close()
		}

		recordBeaconPermitTerminalOutcome(
			logger,
			permit,
			participation.TerminalOutcomeCompleted,
			participation.TerminalEvidence{
				Kind: participation.TerminalEvidenceForwarderClosed,
			},
		)
	}()
}

// ResumeSigningIfEligible enables a client to rejoin the ongoing signing process
// after it was crashed or restarted and if it belongs to the signing group.
func (n *node) ResumeSigningIfEligible() {
	isEntryInProgress, err := n.beaconChain.IsEntryInProgress()
	if err != nil {
		logger.Errorf(
			"failed checking if an entry is in progress: [%v]",
			err,
		)
		return
	}

	if isEntryInProgress {
		previousEntry, err := n.beaconChain.CurrentRequestPreviousEntry()
		if err != nil {
			logger.Errorf(
				"failed to get a previous entry for the current request: [%v]",
				err,
			)
			return
		}
		entryStartBlock, err := n.beaconChain.CurrentRequestStartBlock()
		if err != nil {
			logger.Errorf(
				"failed to get a start block for the current request: [%v]",
				err,
			)
			return
		}
		groupPublicKey, err := n.beaconChain.CurrentRequestGroupPublicKey()
		if err != nil {
			logger.Errorf(
				"failed to get a group public key for the current request: [%v]",
				err,
			)
			return
		}

		logger.Infof(
			"attempting to rejoin the current signing process [0x%x]",
			groupPublicKey,
		)
		// The on-chain liveness of the request was verified just above:
		// IsEntryInProgress reported an entry in progress and the canonical
		// anchor is the on-chain current request start block. That is the
		// verification the gate's Resume path requires from its caller.
		n.generateRelayEntry(
			previousEntry,
			groupPublicKey,
			entryStartBlock.Uint64(),
			true,
		)
	}
}

// MonitorRelayEntry is listetning to the chain for a new relay entry.
// When a processing group which is supposed to deliver a relay entry does not
// fulfill its work, then this node notifies the chain about it. In the case of
// delivering a relay entry by a processing group, this node does nothing.
//
// The monitoring runs under a participation permit anchored at the relay
// request block: a timeout report is a penalty commit, so a legacy permit
// cannot report at or after the cutover block and no permit can report once
// quiescence begins.
//
// The previous entry the monitored request is signing over is carried along
// because it is how the beacon identifies that request among the ones made in
// the same block, and the monitor has to name the request exactly to read back
// whether its own report terminated it.
func (n *node) MonitorRelayEntry(
	relayRequestPreviousEntry []byte,
	relayRequestBlockNumber uint64,
) {
	logger.Infof("monitoring chain for a new relay entry")

	if n.participationGate == nil {
		// The monitor exists only to file the penalty report; without a gate
		// there is no fenced way to do that. Fail closed.
		logger.Errorf(
			"no participation gate; refusing to monitor the relay entry",
		)
		return
	}

	permit, err := n.participationGate.Begin(
		participation.BeaconTimeoutReport,
		relayRequestBlockNumber,
		beaconRelayPermitIdentity(relayRequestBlockNumber, "timeout-monitor"),
	)
	if err != nil {
		logger.Warnf(
			"relay entry monitoring refused by the participation gate: [%v]",
			err,
		)
		return
	}
	// timeoutSettlement holds the beacon's own record of the request this
	// monitor's report terminated, which is the only durable state this
	// ceremony can create. The deferred recorder below reads its final value.
	var timeoutSettlement *event.RelayEntryTimeoutSettlement

	// The terminal outcome is registered after the release so it runs first and
	// reaches the permit while it is still open.
	defer permit.Close()
	defer func() {
		recordRelayTimeoutTerminalOutcome(
			logger,
			permit,
			relayRequestBlockNumber,
			timeoutSettlement,
		)
	}()

	blockCounter, err := n.beaconChain.BlockCounter()
	if err != nil {
		logger.Errorf("failed to get block counter: [%v]", err)
		return
	}

	chainConfig := n.beaconChain.GetConfig()

	// The block the group runs out of time at is derived before anything is
	// watched, because the derivation is what authorizes the report: a timeout
	// block that overflowed would name a block already passed and turn the
	// waiter below into an immediate false penalty.
	timeoutBlock, err := relayEntryTimeoutBlock(
		relayRequestBlockNumber,
		chainConfig.RelayEntryTimeout,
	)
	if err != nil {
		logger.Errorf(
			"refusing to monitor the relay entry of block [%v]; its timeout "+
				"block cannot be derived: [%v]",
			relayRequestBlockNumber,
			err,
		)
		return
	}

	timeoutWaiterChannel, err := blockCounter.BlockHeightWaiter(timeoutBlock)
	if err != nil {
		logger.Errorf("waiter for a relay entry timeout block failed: [%v]", err)
		return
	}

	// The buffer lets an in-flight event callback complete after this
	// function returned on cancellation, instead of blocking forever.
	onEntrySubmittedChannel := make(chan *event.RelayEntrySubmitted, 1)

	subscription := n.beaconChain.OnRelayEntrySubmitted(
		func(event *event.RelayEntrySubmitted) {
			onEntrySubmittedChannel <- event
		},
	)
	// The subscription outlives the timeout branch. A report is only a penalty
	// if the request left the beacon because of it, and a late entry delivered
	// while the report is being resolved is what distinguishes the two, so the
	// monitor keeps watching deliveries until it has stopped asking.
	defer subscription.Unsubscribe()

	for {
		select {
		case blockNumber := <-timeoutWaiterChannel:
			// The last-moment penalty fence: a late legacy timeout at or
			// after the cutover block, or any timeout during quiescence,
			// must not create new penalty state.
			if err := permit.CheckCommit(
				"beacon_relay_timeout_report",
				participation.PenaltyCommit,
			); err != nil {
				logger.Warnf(
					"relay entry timeout report refused by the release "+
						"gate: [%v]",
					err,
				)
				return
			}

			logger.Warnf(
				"relay entry was not submitted on time, reporting timeout at block [%v]",
				blockNumber,
			)
			err = n.beaconChain.ReportRelayEntryTimeout()
			if err != nil {
				logger.Errorf("could not report a relay entry timeout: [%v]", err)
				return
			}
			// The call returning only means a provider took the transaction.
			// The beacon decides whether a penalty exists, so the monitor
			// asks it before claiming one.
			timeoutSettlement = n.relayTimeoutReportSettled(
				permit.Context(),
				logger,
				blockCounter,
				relayRequestBlockNumber,
				relayRequestPreviousEntry,
				onEntrySubmittedChannel,
			)
			return
		case entry := <-onEntrySubmittedChannel:
			logger.Infof(
				"relay entry was submitted by the selected group on time at block [%v]",
				entry.BlockNumber,
			)
			return
		case <-permit.Context().Done():
			logger.Warnf(
				"relay entry monitoring canceled by the participation "+
					"gate: [%v]",
				context.Cause(permit.Context()),
			)
			return
		}
	}
}

// GenerateRelayEntry is triggered for a new relay request and checks if this
// client is one of the group members selected to create a new relay entry.
// If it is, this client enters the threshold signature creation process and,
// upon successfully completing it, submits the signature as a new relay entry.
// Note that this function returns immediately after determining whether the
// node is or is not a member of the requested group, and signature creation
// and submission is performed in a background goroutine.
func (n *node) GenerateRelayEntry(
	previousEntry []byte,
	groupPublicKey []byte,
	startBlockHeight uint64,
) {
	n.generateRelayEntry(previousEntry, groupPublicKey, startBlockHeight, false)
}

// generateRelayEntry runs the relay entry signing for every local membership,
// each under its own participation permit anchored at the on-chain relay
// request start block. The resume flag selects the gate's restart path, which
// requires the caller to have verified on chain that the request is still
// live.
func (n *node) generateRelayEntry(
	previousEntry []byte,
	groupPublicKey []byte,
	startBlockHeight uint64,
	resume bool,
) {
	relayLogger := logger.With(
		zap.String("groupPublicKey", fmt.Sprintf("0x%x", groupPublicKey)),
		zap.String("previousEntry", fmt.Sprintf("0x%x", previousEntry)),
	)

	memberships := n.groupRegistry.GetGroup(groupPublicKey)

	if len(memberships) < 1 {
		return
	}

	if n.participationGate == nil {
		// The gate is mandatory in production; signing without it would select
		// a protocol mode implicitly. Fail closed.
		relayLogger.Errorf(
			"no participation gate; refusing to sign the relay entry",
		)
		return
	}

	channel, err := n.netProvider.BroadcastChannelFor(memberships[0].ChannelName)
	if err != nil {
		relayLogger.Errorf("could not create broadcast channel: [%v]", err)
		return
	}

	entry.RegisterUnmarshallers(channel)

	// Each signer of the given group should have the same picture of other
	// group operators. Otherwise, they would not be in the group registry.
	// That said, take the group operators from the first signer.
	groupMembers := n.groupRegistry.GetGroup(groupPublicKey)[0].
		Signer.
		GroupOperators()

	membershipValidator := group.NewMembershipValidator(
		relayLogger,
		groupMembers,
		n.beaconChain.Signing(),
	)

	err = channel.SetFilter(membershipValidator.IsInGroup)
	if err != nil {
		relayLogger.Errorf(
			"could not set filter for channel [%v]: [%v]",
			channel.Name(),
			err,
		)
	}

	blockCounter, err := n.beaconChain.BlockCounter()
	if err != nil {
		relayLogger.Errorf("failed to get block counter: [%v]", err)
		return
	}

	chainConfig := n.beaconChain.GetConfig()

	issuePermit := n.participationGate.Begin
	if resume {
		issuePermit = n.participationGate.Resume
	}

	for _, member := range memberships {
		// One participation permit per local membership, anchored at the
		// on-chain relay request start block: all share exchange and
		// submission run under it and a refusal is a gate decision, not an
		// ordinary signing failure.
		permit, err := issuePermit(
			participation.BeaconRelaySigning,
			startBlockHeight,
			beaconRelayPermitIdentity(
				startBlockHeight,
				fmt.Sprint(member.Signer.MemberID()),
				member.Signer.MemberID(),
			),
		)
		if err != nil {
			relayLogger.Warnf(
				"[member:%v] relay entry signing refused by the "+
					"participation gate: [%v]",
				member.Signer.MemberID(),
				err,
			)
			continue
		}

		go func(member *registry.Membership, permit participation.Permit) {
			defer permit.Close()

			n.protocolLatch.Lock()
			defer n.protocolLatch.Unlock()

			relayEntry, incorporated, err := entry.SignAndSubmit(
				permit.Context(),
				relayLogger,
				blockCounter,
				channel,
				n.beaconChain,
				previousEntry,
				chainConfig.HonestThreshold,
				member.Signer,
				startBlockHeight,
				permit,
			)
			// The recovered entry, not the submission's fate, is this
			// ceremony's node-owned terminal disposition: a member that never
			// reached the honest threshold left no result behind. The
			// memberships whose shares it was recovered from travel with it, so
			// the record says who produced the entry rather than only that one
			// exists.
			recordRelayEntryTerminalOutcome(
				relayLogger,
				permit,
				startBlockHeight,
				member.Signer.GroupPublicKeyBytesCompressed(),
				previousEntry,
				relayEntry,
				incorporated,
				memberships,
			)
			if err != nil {
				if participation.IsGateRefusal(err) {
					relayLogger.Warnf(
						"relay entry signing canceled by the participation "+
							"gate: [%v]",
						err,
					)
					return
				}
				relayLogger.Errorf(
					"error creating threshold signature: [%v]",
					err,
				)
				return
			}
		}(member, permit)
	}
}

// channelNameForPublicKey takes group public key represented by marshalled
// G2 point and transforms it into a broadcast channel name.
// Broadcast channel name for group is the hexadecimal representation of
// compressed public key of the group.
func channelNameForPublicKeyBytes(groupPublicKey []byte) (string, error) {
	g2 := new(bn256.G2)

	if _, err := g2.Unmarshal(groupPublicKey); err != nil {
		return "", fmt.Errorf("could not create channel name: [%v]", err)
	}

	return channelNameForPublicKey(g2), nil
}

// channelNameForPublicKey takes group public key represented by G2 point
// and transforms it into a broadcast channel name.
// Broadcast channel name for group is the hexadecimal representation of
// compressed public key of the group.
func channelNameForPublicKey(groupPublicKey *bn256.G2) string {
	altbn128GroupPublicKey := altbn128.G2Point{G2: groupPublicKey}
	return hex.EncodeToString(altbn128GroupPublicKey.Compress())
}
