#!/usr/bin/env bash
#
# Self-test for rehearse.sh's fail-closed source binding.
#
# Builds throwaway repositories shaped like the dispatched checkout and like
# the CI build image's tree — context-excluded paths absent, the gen/
# binding and _address families regenerated from artifacts, gitignored build
# outputs present, the committed ignore rules dropped — and proves the
# verifier accepts exactly the image's documented construction and nothing
# else, and that no regenerated byte survives verification: every
# regenerated family is checked restored on disk to the committed bytes,
# arbitrary contents included, while an unrestorable path, an untracked
# injection, and every tamper of committed code fail.
#
# All of that rests on a classification of the build context written out in
# rehearse.sh, so the last cases prove that classification still matches the
# rules the build's own ignore file carries. They commit the checked-in
# rules, rewritings of them, and drifts of them into throwaway trees, and
# require the mirror check to accept the rules as they stand and as spellings
# only path cleaning resolves; to refuse a dropped rule, an added rule, a
# dropped re-inclusion, an absent or ruleless file, and every pattern
# construct it does not model; and to read its rules from the file the
# builder itself would select, which a committed Dockerfile.dockerignore
# takes over from the root .dockerignore entirely.
#
# Which file that is, in turn, is selected by a Dockerfile named in a workflow
# rather than in this scaffold, so the last cases move the real build step onto
# another Dockerfile and another context and require the resolution to follow
# it, the path filters that gate this whole check to be held to it, and every
# step shape the resolution does not model to be refused rather than guessed
# at. Runs anywhere bash and git exist; everything lives under mktemp and this
# repository is only ever read.

set -euo pipefail

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=/dev/null
source "${TEST_DIR}/rehearse.sh"

# The verifier reads these from the environment; the container running the
# proof stages exports them, and they must never leak into the cases.
unset PR4109_EXPECTED_SOURCE_COMMIT PR4109_SOURCE_BINDING_MODE

# The build rules the mirror cases compare against, resolved once here: the
# cases below reassign REPO_ROOT inside their subshells to point the verifier
# at a throwaway tree, so the checked-in file has to be named before any of
# them runs.
CHECKED_IN_DOCKERIGNORE="${REPO_ROOT}/.dockerignore"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/pr4109-source-binding.XXXXXX")"
trap 'rm -rf "${WORK}"' EXIT

PASS=0
FAILED=0
ORIGIN_SHA=""
CASE_RC=0
CASE_OUT=""

# Every git invocation pins its identity and disables signing so the cases
# behave identically on a workstation and inside the CI build image.
git_q() {
  git -c user.name=rehearsal -c user.email=rehearsal@invalid \
    -c commit.gpgsign=false -c init.defaultBranch=main "$@"
}

# The build step and the path filters a fixture carries unless a case is
# proving a drift in one of them: the shape the checked-in workflows have,
# reduced to what the resolution actually reads out of them.
DEFAULT_BUILD_STEP="        uses: ${BUILD_ACTION}@v5
        with:
          target: build-docker
          load: true
          context: ."
DEFAULT_PATH_FILTERS="scripts/release/pr4109/**
${REHEARSAL_WORKFLOW}
${SCAFFOLD_LINT_WORKFLOW}
.dockerignore
Dockerfile.dockerignore
.gitignore
Dockerfile
Makefile"

# The two scaffold workflows every fixture carries: the dispatch whose build
# step names the Dockerfile and the context it is compiled from, and the lint
# whose path filters have to cover every input that naming depends on. The
# mirror check resolves both before it compiles a single ignore rule, so a
# fixture without them would prove nothing about the rules it does carry.
#
# The build step's body and the filter entries are given whole so a case can
# shape exactly the drift it means to prove. The step that follows the build
# one carries a block scalar on purpose: its content is indented past the
# step's own keys, and a parser that read it as structure would slice the
# build step's inputs somewhere else entirely.
write_scaffold_workflows() {
  local repo="$1" step="$2" filters="$3" entry
  mkdir -p "${repo}/$(dirname "${REHEARSAL_WORKFLOW}")"
  {
    printf 'name: Cutover Rehearsal\non:\n  workflow_dispatch:\njobs:\n'
    printf '  local-proofs:\n    runs-on: ubuntu-latest\n    steps:\n'
    printf '      - uses: actions/checkout@v4\n'
    printf '      - name: Build Docker Build Image\n'
    printf '%s\n' "${step}"
    printf '      - name: Run cutover gate local proofs\n'
    printf '        run: |\n'
    printf '          docker run go-build-env \\\n'
    printf '            ./scripts/release/pr4109/rehearse.sh local-proofs\n'
  } >"${repo}/${REHEARSAL_WORKFLOW}"

  {
    printf 'name: Cutover Scaffold Lint\non:\n'
    printf '  push:\n    branches:\n      - main\n    paths:\n'
    while IFS= read -r entry; do
      [[ -n "${entry}" ]] && printf '      - "%s"\n' "${entry}"
    done <<<"${filters}"
    printf '  pull_request:\n    paths:\n'
    while IFS= read -r entry; do
      [[ -n "${entry}" ]] && printf '      - "%s"\n' "${entry}"
    done <<<"${filters}"
    printf 'jobs:\n  scaffold-lint:\n    runs-on: ubuntu-latest\n    steps:\n'
    printf '      - uses: actions/checkout@v4\n'
  } >"${repo}/${SCAFFOLD_LINT_WORKFLOW}"
}

# The same build step and filters after the build has been moved onto another
# Dockerfile in another directory: the ignore file that name selects moves with
# it, and so does everything the gate has to run on.
ALT_BUILD_STEP="        uses: ${BUILD_ACTION}@v5
        with:
          target: build-docker
          context: .
          file: build/Alt.Dockerfile"
ALT_PATH_FILTERS="scripts/release/pr4109/**
${REHEARSAL_WORKFLOW}
${SCAFFOLD_LINT_WORKFLOW}
.dockerignore
build/Alt.Dockerfile.dockerignore
.gitignore
build/Alt.Dockerfile
Makefile"

# Commit whatever a case has written into a built fixture. The resolution
# reads the workflows and the ignore rules from the commit, so an uncommitted
# drift would not exist as far as it is concerned.
commit_fixture() {
  (
    cd "$1"
    git_q add -Af
    git_q commit -q -m 'fixture drift'
  )
}

# Rewrite a built fixture's scaffold workflows, and commit them together with
# whatever else the case has staged.
recommit_scaffold_workflows() {
  local repo="$1" step="$2" filters="$3"
  write_scaffold_workflows "${repo}" "${step}" "${filters}"
  commit_fixture "${repo}"
}

# Lay down the alternate Dockerfile the cases move the build onto, beside the
# ignore file its name selects — a copy of the given rules, so a case can prove
# both that those rules are the ones read and that a drift in them is caught.
plant_alternate_dockerfile() {
  local repo="$1" ignore="$2"
  mkdir -p "${repo}/build"
  echo 'FROM scratch' >"${repo}/build/Alt.Dockerfile"
  cp "${ignore}" "${repo}/build/Alt.Dockerfile.dockerignore"
}

# A miniature of the real tree holding one representative of every family
# the classifier distinguishes: context-excluded paths, the protected
# committed generated code (gen/pb, gen/gen.go, gen/cmd/cmd.go), the
# regenerated binding and _address families, plain source, and ignore rules
# covering the image's build outputs.
make_origin() {
  local repo="${WORK}/origin"
  mkdir -p "${repo}"
  (
    cd "${repo}"
    git_q init -q
    printf '/keep-client\ntmp/\n/pkg/chain/**/gen/_contracts/\n/pkg/chain/**/gen/abi/*.abi\n' \
      >.gitignore
    mkdir -p .github/workflows .clusterfuzzlite docs scripts config \
      pkg/tbtc/gen/pb \
      pkg/chain/ethereum/beacon/gen/abi \
      pkg/chain/ethereum/beacon/gen/cmd \
      pkg/chain/ethereum/beacon/gen/contract \
      pkg/chain/ethereum/beacon/gen/_address \
      solidity/ecdsa
    echo 'jobs:' >.github/workflows/ci.yml
    echo 'fuzz build' >.clusterfuzzlite/build.sh
    echo 'FROM scratch' >Dockerfile
    echo '* @keep-network/core' >CODEOWNERS
    echo '= README' >README.adoc
    echo 'docs' >docs/index.adoc
    echo '#!/bin/sh' >scripts/helper.sh
    echo 'toml' >config/config.toml
    echo 'module example.com/m' >go.mod
    echo 'package main' >main.go
    echo 'package pb // committed protobuf bytes' \
      >pkg/tbtc/gen/pb/message.pb.go
    echo 'package gen // committed generator directives' \
      >pkg/chain/ethereum/beacon/gen/gen.go
    echo 'package cmd // committed root command' \
      >pkg/chain/ethereum/beacon/gen/cmd/cmd.go
    echo 'package cmd // committed binding command' \
      >pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
    echo 'package abi // committed binding abi' \
      >pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go
    echo 'package contract // committed binding' \
      >pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go
    touch pkg/chain/ethereum/beacon/gen/_address/.keep
    : >pkg/chain/ethereum/beacon/gen/_address/RandomBeacon
    echo 'contract A {}' >solidity/ecdsa/WalletRegistry.sol
    write_scaffold_workflows "${repo}" "${DEFAULT_BUILD_STEP}" \
      "${DEFAULT_PATH_FILTERS}"
    git_q add -A
    git_q commit -q -m 'fixture'
  )
  ORIGIN_SHA="$(git -C "${repo}" rev-parse HEAD)"
}

# A pristine clone of the origin: the dispatched checkout as CI sees it.
make_checkout() {
  local tree="$1"
  git_q clone -q --no-hardlinks "${WORK}/origin" "${tree}"
}

# Reshape a clone the way the Dockerfile builds the image: context-excluded
# paths never copied (ignore rules included), the binding and _address
# families rewritten from downloaded artifacts, the _address placeholder not
# recreated, and the gitignored build outputs present.
make_image_tree() {
  local tree="$1"
  make_checkout "${tree}"
  (
    cd "${tree}"
    rm -rf .gitignore .github Dockerfile CODEOWNERS README.adoc docs \
      scripts solidity
    rm -f pkg/chain/ethereum/beacon/gen/_address/.keep
    printf '0x1111111111111111111111111111111111111111' \
      >pkg/chain/ethereum/beacon/gen/_address/RandomBeacon
    echo 'package contract // regenerated from published artifacts' \
      >pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go
    echo 'package abi // regenerated from published artifacts' \
      >pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go
    echo 'package cmd // regenerated from published artifacts' \
      >pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
    echo 'binary bytes' >keep-client
    mkdir -p 'tmp/contracts/development/@keep-network/random-beacon'
    echo 'tarball bytes' \
      >'tmp/contracts/development/@keep-network/random-beacon/keep-network-random-beacon-2.1.0-dev.24.tgz'
    echo 'abi json' >pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.abi
    mkdir -p pkg/chain/ethereum/beacon/gen/_contracts
    echo 'artifact json' \
      >pkg/chain/ethereum/beacon/gen/_contracts/RandomBeacon.json
  )
}

# A throwaway checkout carrying a given .dockerignore and one tracked path
# per family the verifier's build-context classification distinguishes:
# context-excluded paths, the protected committed generated code, the
# regenerated binding and _address families, a non-Go file inside a gen/
# tree, and plain source. The mirror cases commit the checked-in
# .dockerignore or a deliberate drift of it, so what they compare against is
# the real rule set.
#
# An optional third argument commits a Dockerfile-specific ignore file
# alongside the root one. The builder reads that file instead of the root
# .dockerignore whenever it exists, so the precedence cases hand the two
# files different rules and require the verifier to follow the build.
make_context_repo() {
  local repo="$1" ignore="$2" dockerfile_ignore="${3:-}"
  mkdir -p "${repo}"
  (
    cd "${repo}"
    git_q init -q
    cp "${ignore}" .dockerignore
    if [[ -n "${dockerfile_ignore}" ]]; then
      cp "${dockerfile_ignore}" Dockerfile.dockerignore
    fi
    mkdir -p .github/workflows .clusterfuzzlite docs infrastructure scripts \
      config solidity/ecdsa pkg/tbtc/gen/pb \
      pkg/chain/ethereum/beacon/gen/abi \
      pkg/chain/ethereum/beacon/gen/cmd \
      pkg/chain/ethereum/beacon/gen/_address
    echo 'jobs:' >.github/workflows/ci.yml
    echo 'fuzz build' >.clusterfuzzlite/build.sh
    echo 'FROM scratch' >Dockerfile
    echo '* @keep-network/core' >CODEOWNERS
    echo '= README' >README.adoc
    echo 'docs' >docs/index.adoc
    echo 'kind: Deployment' >infrastructure/kube.yaml
    echo '#!/bin/sh' >scripts/helper.sh
    echo 'toml' >config/config.toml
    echo 'contract A {}' >solidity/ecdsa/WalletRegistry.sol
    echo 'package main' >main.go
    echo 'package pb' >pkg/tbtc/gen/pb/message.pb.go
    echo 'package gen' >pkg/chain/ethereum/beacon/gen/gen.go
    echo 'abi:' >pkg/chain/ethereum/beacon/gen/Makefile
    echo 'package cmd' >pkg/chain/ethereum/beacon/gen/cmd/cmd.go
    echo 'package cmd' >pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
    echo 'package abi' >pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go
    : >pkg/chain/ethereum/beacon/gen/_address/RandomBeacon
    write_scaffold_workflows "${repo}" "${DEFAULT_BUILD_STEP}" \
      "${DEFAULT_PATH_FILTERS}"
    git_q add -Af
    git_q commit -q -m 'context fixture'
  )
}

# Derive a drifted .dockerignore from the checked-in one. A filter that
# removes nothing would make its case pass for the wrong reason — the rules
# it names having since been renamed or dropped — so an ineffective filter is
# reported as a failure instead of being silently tolerated.
drift_dockerignore() {
  local out="$1" filter="$2"
  grep -Ev -- "${filter}" "${CHECKED_IN_DOCKERIGNORE}" >"${out}" || true
  if cmp -s "${out}" "${CHECKED_IN_DOCKERIGNORE}"; then
    printf 'FAIL fixture: /%s/ removes no .dockerignore line; the case built \
on it would prove nothing\n' "${filter}"
    FAILED=$((FAILED + 1))
  fi
}

# Rewrite rules of the checked-in .dockerignore into an equivalent spelling —
# the cases below use it for the forms that only survive path cleaning. Like
# drift_dockerignore, a rewrite that matches nothing is a failure rather than
# a case that passes for having changed nothing.
rewrite_dockerignore() {
  local out="$1"
  shift
  local expr args=()
  for expr in "$@"; do args+=(-e "${expr}"); done
  sed "${args[@]}" "${CHECKED_IN_DOCKERIGNORE}" >"${out}"
  if cmp -s "${out}" "${CHECKED_IN_DOCKERIGNORE}"; then
    printf 'FAIL fixture: the rewrite rewrites no .dockerignore line; the \
case built on it would prove nothing\n'
    FAILED=$((FAILED + 1))
  fi
}

# Append extra rules to the checked-in .dockerignore. The cases use it for
# constructs the verifier must refuse outright, so what precedes them has to
# be the real rule set: a refusal reached before the real rules are read
# would prove nothing about the file the build actually applies.
extend_dockerignore() {
  local out="$1"
  shift
  cat "${CHECKED_IN_DOCKERIGNORE}" >"${out}"
  printf '%s\n' "$@" >>"${out}"
}

# Run verify_build_context_mirror against a throwaway repository in an
# isolated subshell so a fail/exit inside it never kills the test run;
# capture rc and combined output.
run_context_mirror() {
  local root="$1"
  set +e
  CASE_OUT="$(
    (
      # The sourced check reads this; shellcheck cannot see across the
      # source boundary, and the assignment stays in this subshell.
      # shellcheck disable=SC2034
      REPO_ROOT="${root}"
      verify_build_context_mirror
    ) 2>&1
  )"
  CASE_RC=$?
  set -e
}

# Run verify_source_binding against a tree in an isolated subshell so a
# fail/exit inside the verifier never kills the test run; capture rc and
# combined output. Arguments: repo root, expected commit, binding mode.
run_verifier() {
  local root="$1" expected="$2" mode="$3"
  set +e
  CASE_OUT="$(
    (
      # The sourced verifier reads these three; shellcheck cannot see
      # across the source boundary.
      # shellcheck disable=SC2034
      REPO_ROOT="${root}"
      # shellcheck disable=SC2034
      PR4109_EXPECTED_SOURCE_COMMIT="${expected}"
      # shellcheck disable=SC2034
      PR4109_SOURCE_BINDING_MODE="${mode}"
      verify_source_binding
    ) 2>&1
  )"
  CASE_RC=$?
  set -e
}

# Assert a file's post-run bytes. Restoration must leave exactly the
# committed bytes on disk — those are the bytes any following test
# compiles — so the proof is the file content, not the verifier's output.
assert_file_is() {
  local desc="$1" file="$2" want="$3"
  if [[ ! -f "${file}" ]]; then
    printf 'FAIL %s: %s is missing\n' "${desc}" "${file}"
    FAILED=$((FAILED + 1))
    return
  fi
  local got
  got="$(cat "${file}")"
  if [[ "${got}" != "${want}" ]]; then
    printf 'FAIL %s: %s holds [%s], want [%s]\n' \
      "${desc}" "${file}" "${got}" "${want}"
    FAILED=$((FAILED + 1))
    return
  fi
  printf 'ok   %s\n' "${desc}"
  PASS=$((PASS + 1))
}

# Assert the captured rc and that the output matches every given pattern.
check() {
  local desc="$1" want_rc="$2"
  shift 2
  if [[ "${CASE_RC}" -ne "${want_rc}" ]]; then
    printf 'FAIL %s: rc %s, want %s\n--- output ---\n%s\n--------------\n' \
      "${desc}" "${CASE_RC}" "${want_rc}" "${CASE_OUT}"
    FAILED=$((FAILED + 1))
    return
  fi
  local pattern
  for pattern in "$@"; do
    if ! printf '%s\n' "${CASE_OUT}" | grep -Eq -- "${pattern}"; then
      printf 'FAIL %s: output missing /%s/\n--- output ---\n%s\n--------------\n' \
        "${desc}" "${pattern}" "${CASE_OUT}"
      FAILED=$((FAILED + 1))
      return
    fi
  done
  printf 'ok   %s\n' "${desc}"
  PASS=$((PASS + 1))
}

make_origin

# --- exact mode -------------------------------------------------------------

T="${WORK}/exact-clean"
make_checkout "${T}"
run_verifier "${T}" "${ORIGIN_SHA}" ""
check "exact: pristine dispatched checkout passes" 0 \
  "verified against the dispatched SHA"

T="${WORK}/exact-dirty"
make_checkout "${T}"
echo tampered >>"${T}/main.go"
run_verifier "${T}" "${ORIGIN_SHA}" ""
check "exact: any divergence fails" 1 "tree diverges"

run_verifier "${T}" "" ""
check "unbound: dirty tree stamps -dirty instead of failing" 0 "dirty"

T="${WORK}/exact-mismatch"
make_checkout "${T}"
run_verifier "${T}" "0000000000000000000000000000000000000000" ""
check "exact: dispatched-SHA mismatch fails" 1 "source binding mismatch"

T="${WORK}/exact-badmode"
make_checkout "${T}"
run_verifier "${T}" "${ORIGIN_SHA}" "trust-me"
check "unknown binding mode fails" 1 "unknown PR4109_SOURCE_BINDING_MODE"

# --- build-image mode -------------------------------------------------------

T="${WORK}/img-clean"
make_image_tree "${T}"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: the image's designed divergence passes, restored" 0 \
  "verified against the dispatched SHA inside the build image" \
  "9 context-excluded absence\(s\); 5 regenerated tracked file\(s\) restored" \
  "gen/contract/RandomBeacon\.go committed sha256 [0-9a-f]{64} \(pre-restore image sha256 [0-9a-f]{64}\)" \
  "gen/_address/RandomBeacon committed sha256 [0-9a-f]{64} \(pre-restore image sha256 [0-9a-f]{64}\)" \
  "gen/_address/\.keep committed sha256 [0-9a-f]{64} \(absent from the image\)" \
  "resolved contract artifact tarballs" \
  "keep-network-random-beacon-2\.1\.0-dev\.24\.tgz sha256 [0-9a-f]{64}"
assert_file_is "build-image: the tested contract binding is the committed \
bytes after verification" \
  "${T}/pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go" \
  'package contract // committed binding'
assert_file_is "build-image: the tested _address value is the committed \
bytes after verification" \
  "${T}/pkg/chain/ethereum/beacon/gen/_address/RandomBeacon" \
  ''

T="${WORK}/img-deletions-only"
make_checkout "${T}"
(cd "${T}" && rm -rf .gitignore .github Dockerfile CODEOWNERS README.adoc \
  docs scripts solidity)
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: expected context-excluded absences alone pass" 0 \
  "9 context-excluded absence\(s\); 0 regenerated tracked file\(s\) restored"

T="${WORK}/img-evil-bindings"
make_image_tree "${T}"
echo 'package contract // arbitrary unreviewed bytes' \
  >"${T}/pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go"
echo 'package abi // arbitrary unreviewed bytes' \
  >"${T}/pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go"
echo 'package cmd // arbitrary unreviewed bytes' \
  >"${T}/pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go"
printf '0x2222222222222222222222222222222222222222' \
  >"${T}/pkg/chain/ethereum/beacon/gen/_address/RandomBeacon"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: arbitrary bytes in every regenerated family never \
survive to be tested" 0 \
  "restored byte-exact from the dispatched"
assert_file_is "build-image: arbitrary contract binding bytes are replaced \
by the committed bytes" \
  "${T}/pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go" \
  'package contract // committed binding'
assert_file_is "build-image: arbitrary abi binding bytes are replaced by \
the committed bytes" \
  "${T}/pkg/chain/ethereum/beacon/gen/abi/RandomBeacon.go" \
  'package abi // committed binding abi'
assert_file_is "build-image: arbitrary binding command bytes are replaced \
by the committed bytes" \
  "${T}/pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go" \
  'package cmd // committed binding command'
assert_file_is "build-image: arbitrary _address bytes are replaced by the \
committed bytes" \
  "${T}/pkg/chain/ethereum/beacon/gen/_address/RandomBeacon" \
  ''

T="${WORK}/img-unrestorable"
make_image_tree "${T}"
rm "${T}/pkg/chain/ethereum/beacon/gen/_address/RandomBeacon"
mkdir "${T}/pkg/chain/ethereum/beacon/gen/_address/RandomBeacon"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: a regenerated path that cannot be restored fails" 1 \
  "could not restore"

T="${WORK}/img-injected-binding"
make_image_tree "${T}"
echo 'package contract // injected implementation' \
  >"${T}/pkg/chain/ethereum/beacon/gen/contract/Injected.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: an untracked file inside a regenerated family is fatal" 1 \
  "\?\? pkg/chain/ethereum/beacon/gen/contract/Injected\.go" \
  "beyond what the image build produces"

T="${WORK}/img-outputs-only"
make_image_tree "${T}"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: gitignored build outputs are classified by the restored \
committed ignore rules" 0 \
  "verified against the dispatched SHA inside the build image"

T="${WORK}/img-mismatch"
make_image_tree "${T}"
run_verifier "${T}" "1111111111111111111111111111111111111111" build-image
check "build-image: dispatched-SHA mismatch fails" 1 "source binding mismatch"

T="${WORK}/img-nogit"
make_image_tree "${T}"
rm -rf "${T}/.git"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: unreadable git metadata fails" 1 \
  "no readable git metadata"

T="${WORK}/img-untracked"
make_image_tree "${T}"
echo 'package tbtc' >"${T}/pkg/tbtc/injected.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: an untracked source file fails" 1 \
  "\?\? pkg/tbtc/injected\.go" "beyond what the image build produces"

T="${WORK}/img-pb"
make_image_tree "${T}"
echo '// tampered' >>"${T}/pkg/tbtc/gen/pb/message.pb.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: modified committed gen/pb code fails" 1 \
  "M pkg/tbtc/gen/pb/message\.pb\.go"

T="${WORK}/img-gengo"
make_image_tree "${T}"
echo '// tampered' >>"${T}/pkg/chain/ethereum/beacon/gen/gen.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: modified committed gen/gen.go fails" 1 \
  "M pkg/chain/ethereum/beacon/gen/gen\.go"

T="${WORK}/img-cmdgo"
make_image_tree "${T}"
echo '// tampered' >>"${T}/pkg/chain/ethereum/beacon/gen/cmd/cmd.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: modified committed gen/cmd/cmd.go fails" 1 \
  "M pkg/chain/ethereum/beacon/gen/cmd/cmd\.go"

T="${WORK}/img-source"
make_image_tree "${T}"
echo '// tampered' >>"${T}/main.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: modified plain source fails" 1 "M main\.go"

T="${WORK}/img-deleted-source"
make_image_tree "${T}"
rm "${T}/main.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: deleted plain source fails" 1 "D main\.go"

T="${WORK}/img-missing-binding"
make_image_tree "${T}"
rm "${T}/pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: a binding the image failed to regenerate fails" 1 \
  "D pkg/chain/ethereum/beacon/gen/contract/RandomBeacon\.go"

T="${WORK}/img-badignore"
make_image_tree "${T}"
printf '*\n' >"${T}/.gitignore"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: a present-but-tampered .gitignore is never restored \
over and fails" 1 "M \.gitignore"

T="${WORK}/img-cfl"
make_image_tree "${T}"
rm -rf "${T}/.clusterfuzzlite"
run_verifier "${T}" "${ORIGIN_SHA}" build-image
check "build-image: .clusterfuzzlite absence is never explained away" 1 \
  "D \.clusterfuzzlite/build\.sh"

# --- build-context mirror ---------------------------------------------------
#
# Everything above trusts the verifier's hand-written classification of the
# build context. These cases prove that classification is still the one
# .dockerignore describes, and that each way it can drift away from the real
# build inputs is caught rather than silently changing what an image tree is
# allowed to be missing.

T="${WORK}/ctx-agrees"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
run_context_mirror "${T}"
check "context mirror: the checked-in rules and this script agree on every \
family" 0 \
  "21 tracked path\(s\) classified identically" \
  "11 kept out of the build context" \
  "3 excluded from the context but regenerated into the image by design"

# The builder path-cleans every rule before compiling it. Uncleaned
# spellings of rules already in the file must therefore keep classifying the
# same paths: a verifier that compiled them literally would match nothing
# under them and read every path they remove as still in the build context.
T="${WORK}/ctx-uncleaned"
rewrite_dockerignore "${WORK}/dockerignore-uncleaned" \
  's|^scripts/$|./scripts/|' \
  's|^tmp/$|//tmp/|' \
  's|^solidity/$|solidity/ecdsa/../|'
make_context_repo "${T}" "${WORK}/dockerignore-uncleaned"
run_context_mirror "${T}"
check "context mirror: uncleaned rule spellings classify as their cleaned \
form" 0 \
  "21 tracked path\(s\) classified identically" \
  "11 kept out of the build context"

# The same for the segment-spanning wildcard in the placements the file does
# not currently carry: leading, where it has to match through the ancestor
# directories of a path, and trailing, where it swallows the rest of one.
T="${WORK}/ctx-globstar"
rewrite_dockerignore "${WORK}/dockerignore-globstar" \
  's|^infrastructure/$|infrastructure/**|' \
  's|^solidity/$|**/solidity|'
make_context_repo "${T}" "${WORK}/dockerignore-globstar"
run_context_mirror "${T}"
check "context mirror: leading and trailing ** placements classify \
identically" 0 \
  "21 tracked path\(s\) classified identically" \
  "11 kept out of the build context"

# The dangerous direction: the mirror keeps explaining an absence the build
# context no longer produces, so build-image mode would accept a tree missing
# a file the image really was given.
T="${WORK}/ctx-rule-dropped"
drift_dockerignore "${WORK}/dockerignore-no-scripts" '^scripts/$'
make_context_repo "${T}" "${WORK}/dockerignore-no-scripts"
run_context_mirror "${T}"
check "context mirror: a rule dropped from .dockerignore while the mirror \
still enforces it fails" 1 \
  "scripts/helper\.sh: this script explains an absence here" \
  "keeps it in the build context" \
  "no longer mirrors \.dockerignore"

# The safe direction, but still drift: an absence the image legitimately
# produces would be reported as unexplained divergence, and no family this
# script knows accounts for it.
T="${WORK}/ctx-rule-added"
cat "${CHECKED_IN_DOCKERIGNORE}" >"${WORK}/dockerignore-plus-config"
printf 'config/\n' >>"${WORK}/dockerignore-plus-config"
make_context_repo "${T}" "${WORK}/dockerignore-plus-config"
run_context_mirror "${T}"
check "context mirror: a rule added to .dockerignore the mirror does not \
know fails" 1 \
  "config/config\.toml: \.dockerignore keeps this path out" \
  "neither excludes it nor treats it as regenerated"

# The negations decide what the blanket dotfile rule gives back, so losing
# one silently removes a whole tree from the build context.
T="${WORK}/ctx-negation-dropped"
drift_dockerignore "${WORK}/dockerignore-no-cfl" '^!\.clusterfuzzlite'
make_context_repo "${T}" "${WORK}/dockerignore-no-cfl"
run_context_mirror "${T}"
check "context mirror: a dropped re-inclusion is caught, not silently \
absorbed" 1 \
  "\.clusterfuzzlite/build\.sh: \.dockerignore keeps this path out"

T="${WORK}/ctx-absent"
make_checkout "${T}"
run_context_mirror "${T}"
check "context mirror: a commit with no ignore file at all fails closed" 1 \
  "carries neither Dockerfile\.dockerignore nor \.dockerignore"

T="${WORK}/ctx-empty"
printf '# every rule commented out\n\n' >"${WORK}/dockerignore-empty"
make_context_repo "${T}" "${WORK}/dockerignore-empty"
run_context_mirror "${T}"
check "context mirror: a .dockerignore carrying no rule fails closed" 1 \
  "carries no pattern at all"

# The pattern constructs this script does not model. Every one of them reads
# here as a literal and reaches the builder's expression engine carrying a
# meaning instead, so approximating any of them would decide real absences on
# a guess. Each is refused by name rather than compiled.
T="${WORK}/ctx-escape"
extend_dockerignore "${WORK}/dockerignore-escape" 'weird\*name'
make_context_repo "${T}" "${WORK}/dockerignore-escape"
run_context_mirror "${T}"
check "context mirror: an unmodelled backslash escape fails closed" 1 \
  "pattern \[weird\\\\\*name\] carries" \
  "reads as a literal"

T="${WORK}/ctx-class"
extend_dockerignore "${WORK}/dockerignore-class" 'config/[cd]onfig.toml'
make_context_repo "${T}" "${WORK}/dockerignore-class"
run_context_mirror "${T}"
check "context mirror: an unmodelled character class fails closed" 1 \
  "pattern \[config/\[cd\]onfig\.toml\] carries"

# The class form whose negation the builder's expression engine reads the
# other way round from the glob grammar these rules are documented in: `[!x]`
# is every character but `x` to the grammar and any of `!` or `x` to the
# engine. A verifier guessing either reading would be wrong under the other.
T="${WORK}/ctx-class-negation"
extend_dockerignore "${WORK}/dockerignore-class-negation" 'config/[!x]onfig.toml'
make_context_repo "${T}" "${WORK}/dockerignore-class-negation"
run_context_mirror "${T}"
check "context mirror: an unmodelled negated character class fails closed" 1 \
  "pattern \[config/\[!x\]onfig\.toml\] carries"

T="${WORK}/ctx-alternation"
extend_dockerignore "${WORK}/dockerignore-alternation" 'docs|config'
make_context_repo "${T}" "${WORK}/dockerignore-alternation"
run_context_mirror "${T}"
check "context mirror: an unmodelled alternation fails closed" 1 \
  "pattern \[docs[|]config\] carries"

# The builder refuses this one itself and fails the build with it, so a
# verifier that skipped the line would be modelling a build that cannot run.
T="${WORK}/ctx-bare-negation"
extend_dockerignore "${WORK}/dockerignore-bare-negation" '!'
make_context_repo "${T}" "${WORK}/dockerignore-bare-negation"
run_context_mirror "${T}"
check "context mirror: a bare negation line fails closed" 1 \
  "carries a bare \[!\] line"

# --- build-context mirror: which ignore file the build reads ----------------
#
# The builder picks its ignore rules by Dockerfile: a committed
# Dockerfile.dockerignore takes the whole job over from the root
# .dockerignore. Both directions are proved, because a verifier reading the
# root file regardless would keep checking itself against rules the build has
# stopped applying — and would say so in neither its verdict nor its output.

T="${WORK}/ctx-dockerfile-ignore-read"
drift_dockerignore "${WORK}/dockerignore-df-no-scripts" '^scripts/$'
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}" \
  "${WORK}/dockerignore-df-no-scripts"
run_context_mirror "${T}"
check "context mirror: a drift in Dockerfile.dockerignore is caught even \
though the root file is intact" 1 \
  "the build reads from Dockerfile\.dockerignore" \
  "scripts/helper\.sh: this script explains an absence here" \
  "no longer mirrors Dockerfile\.dockerignore"

T="${WORK}/ctx-dockerfile-ignore-precedence"
make_context_repo "${T}" "${WORK}/dockerignore-df-no-scripts" \
  "${CHECKED_IN_DOCKERIGNORE}"
run_context_mirror "${T}"
check "context mirror: a root .dockerignore the build no longer reads \
decides nothing" 0 \
  "the build reads from Dockerfile\.dockerignore" \
  "22 tracked path\(s\) classified identically" \
  "11 kept out of the build context"

# --- build step: which Dockerfile the build compiles ------------------------
#
# And which Dockerfile that is, the workflow that does the building decides —
# not this scaffold. So the cases move the real build step onto another
# Dockerfile in another directory and require the resolution to follow it into
# the ignore file that name selects, in both directions: the rules there have
# to be the ones the mirror is measured against, and a drift in them has to
# fail. A resolution that restated the Dockerfile as a constant would pass
# every one of these while reading a file the build had stopped applying.

T="${WORK}/step-alternate-dockerfile"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
plant_alternate_dockerfile "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${ALT_BUILD_STEP}" "${ALT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: an alternate Dockerfile moves the ignore file the mirror \
is measured against" 0 \
  "compiles build/Alt\.Dockerfile from context \." \
  "the build reads from build/Alt\.Dockerfile\.dockerignore" \
  "23 tracked path\(s\) classified identically" \
  "11 kept out of the build context"

T="${WORK}/step-alternate-dockerfile-drift"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
drift_dockerignore "${WORK}/dockerignore-alt-no-scripts" '^scripts/$'
plant_alternate_dockerfile "${T}" "${WORK}/dockerignore-alt-no-scripts"
recommit_scaffold_workflows "${T}" "${ALT_BUILD_STEP}" "${ALT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a drift in the alternate Dockerfile's ignore file is \
caught, with the root file intact" 1 \
  "the build reads from build/Alt\.Dockerfile\.dockerignore" \
  "scripts/helper\.sh: this script explains an absence here" \
  "no longer mirrors build/Alt\.Dockerfile\.dockerignore"

# The hole the resolution above closes only half of: moving the build onto
# another Dockerfile also moves the ignore file that decides what an image
# tree may be missing, and the gate holding the two together runs only on the
# paths its own filters name. A filter list left behind would leave every
# later change to those files ungated, and the mirror check would keep passing
# on a file nobody was told had changed.
T="${WORK}/step-alternate-unfiltered"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
plant_alternate_dockerfile "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${ALT_BUILD_STEP}" \
  "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: an alternate Dockerfile the lint filters do not cover \
fails closed" 1 \
  "the push filter list does not cover build/Alt\.Dockerfile$" \
  "the push filter list does not cover build/Alt\.Dockerfile\.dockerignore" \
  "the pull_request filter list does not cover build/Alt\.Dockerfile$" \
  "no longer runs on every build input"

T="${WORK}/lint-root-ignore-unfiltered"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${DEFAULT_BUILD_STEP}" \
  "$(grep -vx '\.dockerignore' <<<"${DEFAULT_PATH_FILTERS}")"
run_context_mirror "${T}"
check "build step: a filter list that stops covering the root ignore file \
fails closed" 1 \
  "the push filter list does not cover \.dockerignore" \
  "no longer runs on every build input"

# The gate cannot hold the resolution to the build step if a change to the
# build step does not run it.
T="${WORK}/lint-workflow-unfiltered"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${DEFAULT_BUILD_STEP}" \
  "$(grep -vxF "${REHEARSAL_WORKFLOW}" <<<"${DEFAULT_PATH_FILTERS}")"
run_context_mirror "${T}"
check "build step: a filter list that stops covering the build workflow fails \
closed" 1 \
  "the push filter list does not cover \
\.github/workflows/cutover-rehearsal\.yml" \
  "no longer runs on every build input"

# An exclusion list says which changes are exempt rather than which are
# covered, so a trigger carrying one cannot be read as coverage at all.
T="${WORK}/lint-paths-ignore"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
{
  printf 'name: Cutover Scaffold Lint\non:\n  pull_request:\n'
  printf '    paths-ignore:\n      - "docs/**"\n'
  printf 'jobs:\n  scaffold-lint:\n    runs-on: ubuntu-latest\n    steps:\n'
  printf '      - uses: actions/checkout@v4\n'
} >"${T}/${SCAFFOLD_LINT_WORKFLOW}"
commit_fixture "${T}"
run_context_mirror "${T}"
check "build step: a lint filtering with paths-ignore fails closed" 1 \
  "filters its pull_request trigger with paths-ignore"

# A filter list matching nothing is not a gate that runs on everything, it is
# a gate that runs on nothing — the state carrying an empty list looks like.
T="${WORK}/lint-empty-filter"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${DEFAULT_BUILD_STEP}" ""
run_context_mirror "${T}"
check "build step: a lint filtered to an empty path list fails closed" 1 \
  "filters its push trigger to an empty path list"

# A trigger carrying no filter at all does run on every change, so it covers
# every build input and is accepted — the check is coverage, not ceremony.
T="${WORK}/lint-unfiltered-trigger"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
{
  printf 'name: Cutover Scaffold Lint\non:\n  pull_request:\n'
  printf 'jobs:\n  scaffold-lint:\n    runs-on: ubuntu-latest\n    steps:\n'
  printf '      - uses: actions/checkout@v4\n'
} >"${T}/${SCAFFOLD_LINT_WORKFLOW}"
commit_fixture "${T}"
run_context_mirror "${T}"
check "build step: a lint running on every pull request covers every build \
input" 0 \
  "on all 1 push/pull-request trigger\(s\)" \
  "21 tracked path\(s\) classified identically"

# The state this workflow exists to end: a checker nothing runs until somebody
# remembers to dispatch it.
T="${WORK}/lint-dispatch-only"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
{
  printf 'name: Cutover Scaffold Lint\non:\n  workflow_dispatch:\n'
  printf 'jobs:\n  scaffold-lint:\n    runs-on: ubuntu-latest\n    steps:\n'
  printf '      - uses: actions/checkout@v4\n'
} >"${T}/${SCAFFOLD_LINT_WORKFLOW}"
commit_fixture "${T}"
run_context_mirror "${T}"
check "build step: a lint reachable only by dispatch fails closed" 1 \
  "runs on no push or pull request"

T="${WORK}/lint-absent"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
(cd "${T}" && git_q rm -q "${SCAFFOLD_LINT_WORKFLOW}" &&
  git_q commit -q -m 'drop the lint')
run_context_mirror "${T}"
check "build step: a commit carrying no scaffold lint fails closed" 1 \
  "carries no \.github/workflows/cutover-scaffold-lint\.yml"

# --- build step: the shapes the resolution refuses to guess at --------------
#
# Every one of these resolves to a Dockerfile only by guessing at what the
# workflow parser reads, and a wrong guess picks the wrong ignore file — which
# is the one direction where this scaffold explains a real absence away.

T="${WORK}/step-absent-workflow"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
(cd "${T}" && git_q rm -q "${REHEARSAL_WORKFLOW}" &&
  git_q commit -q -m 'drop the dispatch')
run_context_mirror "${T}"
check "build step: a commit carrying no rehearsal workflow fails closed" 1 \
  "carries no \.github/workflows/cutover-rehearsal\.yml"

T="${WORK}/step-nested-context"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5
        with:
          context: ./solidity" "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a context that is not the repository root fails closed" 1 \
  "builds from context \[solidity\]" \
  "written over repository-relative paths"

T="${WORK}/step-git-context"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5
        with:
          target: build-docker" "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: an unset context — the action's Git context — fails \
closed" 1 \
  "sets no context" \
  "rather than the dispatched checkout"

T="${WORK}/step-no-inputs"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5" \
  "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a build action passing no inputs at all fails closed" 1 \
  "passes no inputs"

T="${WORK}/step-two-actions"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${DEFAULT_BUILD_STEP}
      - name: Build the runtime image
        uses: ${BUILD_ACTION}@v5
        with:
          context: .
          file: build/Alt.Dockerfile" "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a second build action fails closed rather than picking \
one" 1 \
  "has 2 docker/build-push-action steps"

T="${WORK}/step-no-action"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        run: docker build ." \
  "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a workflow that no longer uses the build action fails \
closed" 1 \
  "has no docker/build-push-action step"

# The value is decided at dispatch time, so no reading of the committed bytes
# can say which Dockerfile the build compiled.
T="${WORK}/step-expression"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5
        with:
          context: .
          file: \${{ inputs.dockerfile }}" "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a Dockerfile decided by a workflow expression fails \
closed" 1 \
  "writes its Dockerfile as a workflow expression"

T="${WORK}/step-flow-inputs"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5
        with: {context: ., file: build/Alt.Dockerfile}" \
  "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: inputs written as a flow mapping fail closed" 1 \
  "reads only a block mapping"

T="${WORK}/step-missing-dockerfile"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "${ALT_BUILD_STEP}" "${ALT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a Dockerfile the commit does not carry fails closed" 1 \
  "builds Dockerfile \[build/Alt\.Dockerfile\], which the commit under test \
does not carry"

T="${WORK}/step-escaping-dockerfile"
make_context_repo "${T}" "${CHECKED_IN_DOCKERIGNORE}"
recommit_scaffold_workflows "${T}" "        uses: ${BUILD_ACTION}@v5
        with:
          context: .
          file: ../shared/Dockerfile" "${DEFAULT_PATH_FILTERS}"
run_context_mirror "${T}"
check "build step: a Dockerfile outside the build context fails closed" 1 \
  "does not resolve to a path inside the build context"

# ----------------------------------------------------------------------------

printf '%d passed, %d failed\n' "${PASS}" "${FAILED}"
if [[ "${FAILED}" -ne 0 ]]; then
  exit 1
fi
